# -*- coding: utf-8 -*-
"""
Build a Crypto Paper Trading Bot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TRzqYfLdarN9hzziOYuWhaF9m9tbEIPu

**Install Dependencies**
"""

"""**Import dependencies**"""

import os
import pandas as pd
import yfinance as yf
import alpaca as tradeapi
import alpaca_trade_api as tradeapi
import configparser
import pytz
import locale
import pandas_market_calendars as mcal

from alpaca_trade_api.rest import REST, TimeFrame, APIError
import alpaca_trade_api as alpaca
from ta.volatility import BollingerBands
from ta.momentum import RSIIndicator
from ta.trend import sma_indicator
from tqdm import tqdm
from requests_html import HTMLSession
from datetime import datetime
from slack import WebClient
from slack.errors import SlackApiError
import time
from alpaca.data.historical import CryptoHistoricalDataClient
from alpaca.data.requests import CryptoBarsRequest
from alpaca.data.timeframe import TimeFrame
from alpaca.trading.client import TradingClient
from alpaca.trading.requests import MarketOrderRequest
from alpaca.trading.enums import OrderSide, TimeInForce
from datetime import datetime
from dateutil.relativedelta import relativedelta
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Activation, Dense, Dropout, LSTM
from sklearn.preprocessing import MinMaxScaler
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.metrics import mean_absolute_error
import json
import logging
#import config
import asyncio
from lumibot.brokers import Alpaca
from lumibot.backtesting import YahooDataBacktesting
from lumibot.strategies.strategy import Strategy
from lumibot.traders import Trader
from datetime import datetime
from alpaca_trade_api import REST
#from timedelta import Timedelta
time.sleep(1)
from google.colab import drive
drive.mount('/content/drive')


"""**Build a Crypto Paper Trading Bot that is Deployable using Docker.**

The paper trading bot scans the top 250 coins by market cap to identify volatile assets.

**Set Up Your Python Environment**
"""


"""**Create and Import Your Configuration**"""

import os
from dotenv import load_dotenv
from sqlalchemy.orm import declarative_base
from sqlalchemy import Column, Float, ForeignKey, Integer, String, DateTime
from sqlalchemy.orm import relationship, declarative_base
from typing import Literal
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import create_engine
import time
import requests
from datetime import datetime
import logging
from typing import List
from sqlalchemy.orm import sessionmaker
from sqlalchemy.orm import Session
from sqlalchemy.exc import NoResultFound
from typing import List, Optional, Union
from enum import Enum

CG_API_KEY = ""
# for use outside docker
DATABASE_URL= "postgresql://admin:admin@localhost:5432/data"
# Application Settings
TAKE_PROFIT = "20"
STOP_LOSS = "10"
ORDER_AMOUNT = "50"
PRICE_CHANGE = "3"

load_dotenv()
cg_api_key = (CG_API_KEY)
db_url = (DATABASE_URL)

tp = float(TAKE_PROFIT)
sl = float(STOP_LOSS)
qty = float(ORDER_AMOUNT)
price_change = float(PRICE_CHANGE)

"""**Create Models, Build the CoinGecko (API) Service, and Build the Trading Service**"""

Base = declarative_base()

# Create Coin Data Model
class Coin(Base):
    __tablename__ = "coins"
    id = Column(Integer, primary_key=True, autoincrement=True)
    coin_id = Column(String, unique=True, nullable=False)
    symbol = Column(String, unique=True, nullable=False)
    realized_pnl = Column(Float, nullable=True)
    prices = relationship(
        "CoinPrice", back_populates="coin", cascade="all, delete-orphan"
    )
class CoinPrice(Base):
    __tablename__ = "coins_prices"
    id = Column(Integer, primary_key=True, autoincrement=True)
    symbol = Column(String, ForeignKey("coins.symbol"), nullable=False)
    timestamp = Column(DateTime, nullable=False)
    value = Column(Float, nullable=False)
    coin = relationship("Coin", back_populates="prices")

class CoinsDAL:
    def __init__(self, session: Session):
        self.session = session
    def get_all_coins(self) -> List[Coin]:
        return self.session.query(Coin).all()
    def get_coin_by_symbol(self, symbol: str) -> Optional[Coin]:
        try:
            return self.session.query(Coin).filter(Coin.symbol == symbol).one()
        except NoResultFound:
            return None
    def update_coin_pnl(
        self, symbol: str, new_realized_pnl: Optional[float]
    ) -> Optional[Coin]:
        coin = self.get_coin_by_symbol(symbol)
        if coin:
            coin.realized_pnl = new_realized_pnl
            self.session.commit()
            return coin
        return None
    def add_price_to_coin(
        self, symbol: str, timestamp: datetime, value: float
    ) -> Optional[CoinPrice]:
        coin = self.get_coin_by_symbol(symbol)
        if coin:
            new_price = CoinPrice(timestamp=timestamp, value=value, symbol=coin.symbol)
            self.session.add(new_price)
            self.session.commit()
            return new_price
        return None
    def get_coin_prices_by_symbol(self, symbol: str) -> List[CoinPrice]:
        coin = self.get_coin_by_symbol(symbol)
        if coin:
            return (
                self.session.query(CoinPrice)
                .filter(CoinPrice.symbol == coin.id)
                .order_by(CoinPrice.timestamp)
                .all()
            )
        return []
    def get_current_price_for_coin(self, symbol: str) -> Optional[CoinPrice]:
        coin: Union[Coin, CoinPrice] = self.get_coin_by_symbol(symbol)
        if coin and coin.prices:
            # Get the most recent price directly from the related prices
            return max(coin.prices, key=lambda price: price.timestamp)
        return None
    def add_coin(
        self, symbol: str, coin_id: str, realized_pnl: Optional[float] = None
    ) -> Optional[Coin]:
        existing_coin = self.get_coin_by_symbol(symbol)
        if existing_coin:
            return None
        new_coin = Coin(
            symbol=symbol, coin_id=coin_id, realized_pnl=realized_pnl or 0.0, prices=[]
        )
        self.session.add(new_coin)
        self.session.commit()
        return new_coin

# Create Order Model
class PaperOrder(Base):
    __tablename__ = "paper_orders"
    id = Column(Integer, primary_key=True, autoincrement=True)
    timestamp = Column(DateTime, nullable=False)
    buy_price = Column(Float, nullable=False)
    quantity = Column(Float, nullable=False)
    symbol = Column(String, nullable=False)
    direction = Column(String, nullable=False)
    direction: Literal[
        "BUY", "SELL"
    ]  # Type hinting for Python-side checking, not affecting DB schema

class OrdersDAL:
    def __init__(self, session: Session):
        self.session = session
    def insert_order(
        self,
        timestamp: datetime,
        buy_price: float,
        quantity: float,
        symbol: str,
        direction: str,
    ) -> PaperOrder:
        new_order = PaperOrder(
            timestamp=timestamp,
            buy_price=buy_price,
            quantity=quantity,
            symbol=symbol,
            direction=direction,
        )
        self.session.add(new_order)
        self.session.commit()
        return new_order
    def get_order_by_symbol(self, symbol: str) -> Optional[PaperOrder]:
        try:
            return (
                self.session.query(PaperOrder)
                .filter(PaperOrder.symbol == symbol)
                .order_by(PaperOrder.timestamp.desc())
                .first()
            )
        except NoResultFound:
            return None
    def get_all_orders(
        self, direction: Optional[Literal["BUY", "SELL"]] = None
    ) -> List[PaperOrder]:
        query = self.session.query(PaperOrder)
        if direction:
            query = query.filter(PaperOrder.direction == direction)
        return query.all()

# Create Portfolio Model
class PnLEntry(Base):
    __tablename__ = "pnl_entries"
    id = Column(Integer, primary_key=True, autoincrement=True)
    date = Column(DateTime, nullable=False)
    value = Column(Float, nullable=False)
    portfolio_item_id = Column(
        Integer, ForeignKey("portfolio_items.id"), nullable=False
    )
class PortfolioItem(Base):
    __tablename__ = "portfolio_items"
    id = Column(Integer, primary_key=True, autoincrement=True)
    cost_basis = Column(Float, nullable=False)
    total_quantity = Column(Float, nullable=False)
    symbol = Column(String, nullable=False)
    # Relationship with PnLEntry (One-to-Many: One PortfolioItem can have many PnLEntries)
    pnl_entries = relationship(
        "PnLEntry", backref="portfolio_item", cascade="all, delete"
    )

class PortfolioDAL:
    def __init__(self, session: Session):
        self.session = session
    def get_portfolio_item_by_symbol(self, symbol: str) -> Optional[PortfolioItem]:
        try:
            return (
                self.session.query(PortfolioItem)
                .filter(PortfolioItem.symbol == symbol)
                .one()
            )
        except NoResultFound:
            return None
    def insert_portfolio_item(
        self, symbol: str, cost_basis: float, total_quantity: float
    ) -> PortfolioItem:
        new_item = PortfolioItem(
            symbol=symbol, cost_basis=cost_basis, total_quantity=total_quantity
        )
        self.session.add(new_item)
        self.session.commit()
        return new_item
    def update_portfolio_item_by_symbol(
        self,
        symbol: str,
        cost_basis: float,
        additional_quantity: float,
    ) -> Optional[PortfolioItem]:
        portfolio_item = self.get_portfolio_item_by_symbol(symbol)
        if portfolio_item is None:
            return None
        portfolio_item.cost_basis = cost_basis
        portfolio_item.total_quantity += additional_quantity
        self.session.commit()
        return portfolio_item
    def add_pnl_entry_by_symbol(
        self, symbol: str, date: datetime, value: float
    ) -> Optional[PnLEntry]:
        portfolio_item = self.get_portfolio_item_by_symbol(symbol)
        if portfolio_item is None:
            return None
        pnl_entry = PnLEntry(
            date=date, value=value, portfolio_item_id=portfolio_item.id
        )
        self.session.add(pnl_entry)
        self.session.commit()
        return pnl_entry

# Building the CoinGecko (API) Service

# The CoinGecko class needs to perform the following actions:
#Fetch the price of a specific coin using the coin_id.
#Retrieve available base coin pairs (also known as /simple/supported_vs_currencies in the CoinGecko API).
#Get a list of coin data.

class CoinGecko:
    def __init__(self):
        self.root = "https://api.coingecko.com/api/v3"
        self.headers = {
            "accept": "application/json",
            "x-cg-demo-api-key": f"{cg_api_key}",
        }
    def get_price_by_coin_id(self, coin_id: str):
        request_url = self.root + f"/simple/price?ids={coin_id}&vs_currencies=usd"
        response = requests.get(request_url, self.headers).json()
        print(response)
        return response[coin_id]["usd"]
    def get_vs_currencies(self):
        request_url = self.root + "/simple/supported_vs_currencies"
        return requests.get(request_url, self.headers).json()
    def get_coin_list(self) -> List[Coin]:
        request_url = (
            self.root
            + "/coins/markets?order=market_cap_desc&per_page=250&vs_currency=usd&price_change_percentage=1h"
        )
        response = requests.get(request_url, headers=self.headers).json()
        coins = []
        for coin_data in response:
            coin = Coin(
                coin_id=coin_data["id"],
                symbol=coin_data["symbol"],
                realized_pnl=None,
            )
            price = CoinPrice(
                symbol=coin_data["symbol"],
                timestamp=datetime.now(),
                value=coin_data["current_price"],
            )
            coin.prices = [price]
            coin.price_change = coin_data["price_change_percentage_1h_in_currency"]
            coins.append(coin)
        return coins

class Currency(Enum):
    BTC = "btc"
    ETH = "eth"
    LTC = "ltc"
    BCH = "bch"
    BNB = "bnb"
    EOS = "eos"
    XRP = "xrp"
    XLM = "xlm"
    LINK = "link"
    DOT = "dot"
    YFI = "yfi"
    USD = "usd"
    AED = "aed"
    ARS = "ars"
    AUD = "aud"
    BDT = "bdt"
    BHD = "bhd"
    BMD = "bmd"
    BRL = "brl"
    CAD = "cad"
    CHF = "chf"
    CLP = "clp"
    CNY = "cny"
    CZK = "czk"
    DKK = "dkk"
    EUR = "eur"
    GBP = "gbp"
    GEL = "gel"
    HKD = "hkd"
    HUF = "huf"
    IDR = "idr"
    ILS = "ils"
    INR = "inr"
    JPY = "jpy"
    KRW = "krw"
    KWD = "kwd"
    LKR = "lkr"
    MMK = "mmk"
    MXN = "mxn"
    MYR = "myr"
    NGN = "ngn"
    NOK = "nok"
    NZD = "nzd"
    PHP = "php"
    PKR = "pkr"
    PLN = "pln"
    RUB = "rub"
    SAR = "sar"
    SEK = "sek"
    SGD = "sgd"
    THB = "thb"
    TRY = "try"
    TWD = "twd"
    UAH = "uah"
    VEF = "vef"
    VND = "vnd"
    ZAR = "zar"
    XDR = "xdr"
    XAG = "xag"
    XAU = "xau"
    BITS = "bits"
    SATS = "sats"

# Building the Trading Service

# The trading service handles the execution of mock buy and sell operations for
# our paper trading bot.

class TradingService:
    def __init__(self):
        pass
    @staticmethod
    def buy(symbol: str, current_price: float, quantity: float) -> PaperOrder:
        return PaperOrder(
            timestamp=datetime.now(),
            buy_price=current_price,
            quantity=quantity,
            symbol=symbol,
            direction="BUY",
        )
    @staticmethod
    def sell(symbol: str, current_price: float, quantity: float) -> PaperOrder:
        return PaperOrder(
            timestamp=datetime.now(),
            buy_price=current_price,
            quantity=quantity,
            symbol=symbol,
            direction="SELL",
        )
    @staticmethod
    def calculate_cost_basis(
        current_cost_basis: float,
        total_qty: float,
        new_order_qty: float,
        new_order_price: float,
    ) -> float:
        new_total_quantity = total_qty + new_order_qty

        if new_total_quantity == 0:
            return 0  # If all quantities are sold, cost basis resets
        return (
            (current_cost_basis * total_qty) + (new_order_price * new_order_qty)
        ) / new_total_quantity

"""**Putting the Logic Together**

Build the core logic and define the entry point of our Python application.

We populate the database with initial data and pull the top 250 coins from CoinGecko

We then handle buy and sell scenarios for each coin and add a new price entry.

Finally, our algorithm sleeps for 1 hour before repeating the cycle.
"""


db_url = "postgresql://myuser:mypassword@localhost:5432/mydb"
# create a database engine and initialize the session
logging.disable(logging.CRITICAL)
print("Waiting For Database to mount...")
time.sleep(5)
# Create engine and session using the database URL from environment
#engine = create_engine(db_url, echo=True)
try:
    engine = create_engine(db_url, echo=True)
    with engine.connect() as conn:
        print("Connection successful!")
except Exception as e:
    print("Connection failed:", e)
Base.metadata.create_all(engine)
Session = sessionmaker(bind=engine)
session = Session()

# Initialize DALs and Services
coins_dal = CoinsDAL(session)
orders_dal = OrdersDAL(session)
portfolio_dal = PortfolioDAL(session)
cg = CoinGecko()

# function to handle database initialization
def initialize_coin_data():
    if len(coins_dal.get_all_coins()) > 0:
        print("DB already initialized, skipping...")
        return
    cg = CoinGecko()
    all_coins = cg.get_coin_list()
    # Add coins and their initial prices to the list
    for coin in all_coins:
        coins_dal.add_coin(coin.symbol, coin.coin_id)
        coins_dal.add_price_to_coin(
            coin.symbol, coin.prices[0].timestamp, coin.prices[0].value
        )
    print(f"Added {len(all_coins)} coins.")
    print(f"Added Prices to {len(all_coins)} coins.")

# update our coin prices periodically by adding new entries to the coin_prices table
def update_coin_prices() -> List[Coin]:
    db_coins = coins_dal.get_all_coins()
    db_coins_ids = [coin.coin_id for coin in db_coins]
    if len(db_coins) == 0:
        print("There are no coins in the database, cannot add prices")
        return
    coin_list = cg.get_coin_list()
    new_coins = 0
    for coin in coin_list:
        if coin.coin_id not in db_coins_ids:
            new_coins += 1
            coins_dal.add_coin(coin.symbol, coin.coin_id)
        coins_dal.add_price_to_coin(coin.symbol, datetime.now(), coin.prices[0].value)
    print(f"Price updated for {len(db_coins)} coins")
    print(
        f"Inserted {new_coins} coins to the coins table likely due movements in the top 250."
    )
    print(f"coin: {coin}, price_change: {coin.price_change}")
    return coin_list

# function that handles our buy logic and saves buy orders to the database
def handle_buy(coin, current_price):
    if coin.price_change is None:
        print(f"Skipping buy for {coin.symbol}: price_change is None")
        return
    if coin.price_change < price_change:
        return
    order = TradingService.buy(coin.symbol, current_price, qty)
    existing_portfolio = portfolio_dal.get_portfolio_item_by_symbol(order.symbol)
    if existing_portfolio is None:
        portfolio_dal.insert_portfolio_item(
            order.symbol, order.buy_price, order.quantity
        )
        print(
            f"Bought {order.symbol} and inserted new portfolio item for {order.symbol}"
        )
    else:
        cost_basis = TradingService.calculate_cost_basis(
            existing_portfolio.cost_basis,
            existing_portfolio.total_quantity,
            order.quantity,
            order.buy_price,
        )
        portfolio_dal.update_portfolio_item_by_symbol(
            order.symbol, cost_basis, order.quantity
        )
        print(
            f"Bought {order.symbol}. We already hold {order.symbol}, updating existing portfolio with new order data."
        )
    orders_dal.insert_order(
        order.timestamp, order.buy_price, order.quantity, order.symbol, order.direction
    )

# method that handles the sell logic
def handle_sell(coin, current_price):
    buy_orders = orders_dal.get_all_orders("BUY")
    filtered_buy_orders = [order for order in buy_orders if order.symbol == coin.symbol]
    if not filtered_buy_orders:
        return
    for order in filtered_buy_orders:
        stop_loss_price = order.buy_price * (1 - sl / 100)
        take_profit_price = order.buy_price * (1 + tp / 100)
        current_pnl = (current_price - order.buy_price) / order.buy_price * 100
        if current_price <= stop_loss_price:
            sell_order = TradingService.sell(
                order.symbol, current_price, order.quantity
            )
            print(
                f"Stop Loss Triggered: Sold {order.quantity} of {order.symbol} at ${current_price}"
            )
        elif current_price >= take_profit_price:
            sell_order = TradingService.sell(
                order.symbol, current_price, order.quantity
            )
            print(
                f"Take Profit Triggered: Sold {order.quantity} of {order.symbol} at ${current_price}"
            )
        else:
            continue
        orders_dal.insert_order(
            sell_order.timestamp,
            sell_order.buy_price,
            sell_order.quantity,
            sell_order.symbol,
            sell_order.direction,
        )
        coins_dal.update_coin_pnl(order.symbol, current_pnl)

# Since we’re asking for a 1-hour price change for the CoinGecko API, it makes
# sense for our trading bot to run every hour, performing the following tasks:

def main():
    # Populate database with initial data
    initialize_coin_data()
    while True:
        api_coins = update_coin_prices()
        for coin in api_coins:
            current_price = coin.prices[0].value
            handle_buy(coin, current_price)
            handle_sell(coin, current_price)
            portfolio_dal.add_pnl_entry_by_symbol(
                coin.symbol, datetime.now(), coin.prices[0].value
            )
        print("Engine cycle complete, sleeping for 1 hour.")
        time.sleep(60) # 3600

if __name__ == "__main__":
    main()
